# Generated by Django 6.0.2 on 2026-02-15 23:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_capacity', models.PositiveIntegerField(default=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='monitoring.parkingfacility')),
            ],
            options={
                'unique_together': {('facility', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitoring.parkingzone')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.device')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='monitoring__timesta_8cb72b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('power_factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='monitoring.device')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='monitoring__timesta_868f26_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'timestamp'), name='unique_device_timestamp')],
            },
        ),
    ]
